"""Shared location constants and utilities."""

# Country-only locations (no city = not tied to an office, implies remote).
# Used by both the prefilter (_infer_work_arrangement) and
# job_processor (_location_indicates_remote) to consistently detect
# remote work when only a country or region name is given.
COUNTRY_ONLY_LOCATIONS = {
    "us",
    "usa",
    "united states",
    "united states of america",
    "uk",
    "united kingdom",
    "great britain",
    "gb",
    "canada",
    "germany",
    "france",
    "australia",
    "india",
    "netherlands",
    "ireland",
    "singapore",
    "japan",
    "brazil",
    "israel",
    "spain",
    "italy",
    "sweden",
    "norway",
    "denmark",
    "finland",
    "switzerland",
    "portugal",
    "poland",
    "mexico",
    "south korea",
    "new zealand",
    "czech republic",
    "austria",
    "belgium",
    "romania",
    "colombia",
    "argentina",
    "chile",
    # Meta-regions used in job postings
    "emea",
    "apac",
    "latam",
    "americas",
    "north america",
    "europe",
    "asia pacific",
}
